# Generated by Django 3.1.4 on 2020-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20201218_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wallet_adress',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
