# Generated by Django 3.1.4 on 2020-12-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20201219_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='wallet_adress',
            new_name='wallet_address',
        ),
    ]
